package StudentAutomations;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmetkaska
 */
public class AddStudent extends javax.swing.JFrame {

    ArrayList<Student> allStudent = new ArrayList<>();
    Student student;

    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_addStudent_name = new javax.swing.JTextField();
        txt_addStudent_password = new javax.swing.JTextField();
        txt_addStudent_address = new javax.swing.JTextField();
        txt_addStudent_studentNumber = new javax.swing.JTextField();
        txt_addStudent_surname = new javax.swing.JTextField();
        txt_addStudent_telephoneNumber = new javax.swing.JTextField();
        txt_addStudent_department = new javax.swing.JTextField();
        spinner_addStudent_age = new javax.swing.JSpinner();
        btn_createStudent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_createStudent = new javax.swing.JTable();
        btn_addStudent_showStudents = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("- Create Teacher Panel -");

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Name    :");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Password :");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Address :");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Student Number :");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Surname :");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Age :");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Telephone :");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("Department :");

        btn_createStudent.setText("Create Student");
        btn_createStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createStudentActionPerformed(evt);
            }
        });

        table_createStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Surname", "Password", "Age", "Address", "Telephone", "Student Number", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_createStudent);

        btn_addStudent_showStudents.setText("Show Students");
        btn_addStudent_showStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addStudent_showStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_addStudent_address, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addStudent_studentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addStudent_password, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addStudent_name, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner_addStudent_age, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_addStudent_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_addStudent_telephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_createStudent)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_addStudent_department, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_addStudent_showStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txt_addStudent_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addStudent_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txt_addStudent_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner_addStudent_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txt_addStudent_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addStudent_telephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_createStudent))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txt_addStudent_studentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addStudent_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addStudent_showStudents))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createStudentActionPerformed
        // TODO add your handling code here:

        if (txt_addStudent_name.getText().equals("") || txt_addStudent_surname.getText().equals("") || txt_addStudent_password.getText().equals("") || txt_addStudent_telephoneNumber.getText().equals("") || txt_addStudent_department.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Please Fill in the All Gaps!!", "Warning",
                    JOptionPane.WARNING_MESSAGE);

        } else {

            int spinner = Integer.parseInt(spinner_addStudent_age.getValue().toString());
            int number = Integer.parseInt(txt_addStudent_studentNumber.getText());
            student = new Student(txt_addStudent_name.getText(), txt_addStudent_surname.getText(), txt_addStudent_password.getText(), spinner, txt_addStudent_address.getText(), txt_addStudent_telephoneNumber.getText(), number, txt_addStudent_department.getText());

            Connection conn = null;
            DbHelper db = new DbHelper();
            PreparedStatement statement = null;

            try {
                conn = db.getConnection();
                String sql = "Insert Into SchoolAutomation.students (id_students, name, surname, password, age, address, telephone, student_number, department) Values(?,?,?,?,?,?,?,?,?);";
                statement = conn.prepareStatement(sql);
                statement.setInt(1, student.getStudentId());
                statement.setString(2, student.getName());
                statement.setString(3, student.getSurname());
                statement.setString(4, student.getPassword());
                statement.setInt(5, student.getAge());
                statement.setString(6, student.getAddress());
                statement.setString(7, student.getTelephoneNumber());
                statement.setInt(8, student.getStudentNumber());
                statement.setString(9, student.getDepartment());

                statement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registration successfully added 👍");

            } catch (SQLException ex) {
                db.ShowError(ex);
            } finally {
                try {
                    statement.close();

                } catch (SQLException ex) {
                    Logger.getLogger(AddTeacher.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(AddTeacher.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            /*
            DefaultTableModel tblModel = (DefaultTableModel) table_createStudent.getModel();
            String id = Integer.toString(student.getStudentId());
            String[] data = {id, txt_addStudent_name.getText(), txt_addStudent_surname.getText(), txt_addStudent_password.getText(), spinner_addStudent_age.getValue().toString(), txt_addStudent_address.getText(), txt_addStudent_telephoneNumber.getText(), txt_addStudent_studentNumber.getText(), txt_addStudent_department.getText()};
            allStudent.add(student);
            tblModel.addRow(data);
             */
        }
        txt_addStudent_name.setText("");
        txt_addStudent_surname.setText("");
        txt_addStudent_password.setText("");
        txt_addStudent_address.setText("");
        txt_addStudent_telephoneNumber.setText("");
        txt_addStudent_studentNumber.setText("");
        txt_addStudent_department.setText("");
    }//GEN-LAST:event_btn_createStudentActionPerformed

    private void btn_addStudent_showStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addStudent_showStudentsActionPerformed
        // TODO add your handling code here:
        table_createStudent.setModel(new DefaultTableModel(null, new String[]{"id_students", "name", "surname", "password", "age", "address", "telephone", "student_number", "department"}));
        Connection conn = null;
        DbHelper db = new DbHelper();
        
        DefaultTableModel tblModel = (DefaultTableModel) table_createStudent.getModel();
        String sql2 = "Select * From SchoolAutomation.students";

        try {
            conn = db.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql2);
            ResultSet rs = pst.executeQuery();

            String id;
            String number;
            while (rs.next()) {
                id = Integer.toString(rs.getInt("id_students"));
                number = Integer.toString(rs.getInt("student_number"));
                tblModel.addRow(new String[]{id, rs.getString("name"), rs.getString("surname"), rs.getString("password"), rs.getString("age"), rs.getString("address"), rs.getString("telephone"), number, rs.getString("department")});
            }

        } catch (Exception ex) {
            System.out.println("Exception : " + ex);
        }
       finally{
            try {
                
                conn.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(AddTeacher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_addStudent_showStudentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addStudent_showStudents;
    private javax.swing.JButton btn_createStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinner_addStudent_age;
    private javax.swing.JTable table_createStudent;
    private javax.swing.JTextField txt_addStudent_address;
    private javax.swing.JTextField txt_addStudent_department;
    private javax.swing.JTextField txt_addStudent_name;
    private javax.swing.JTextField txt_addStudent_password;
    private javax.swing.JTextField txt_addStudent_studentNumber;
    private javax.swing.JTextField txt_addStudent_surname;
    private javax.swing.JTextField txt_addStudent_telephoneNumber;
    // End of variables declaration//GEN-END:variables
}
